[package]
authors = ["Jason Lee <huacnlee@gmail.com>"]
description = "A linter and formatter for help you improve copywriting, to correct spaces, punctuations between CJK (Chinese, Japanese, Korean)."
edition = "2018"
homepage = "https://github.com/huacnlee/autocorrect"
keywords = ["autocorrect", "lint", "format"]
license = "MIT"
name = "autocorrect"
readme = "../README.md"
repository = "https://github.com/huacnlee/autocorrect"
version = "1.4.4"

[lib]
crate-type = ["cdylib", "rlib"]
name = "autocorrect"
path = "src/lib.rs"
proc-macro = true

[dependencies]
autocorrect-derive = {path = "../autocorrect-derive"}
difference = "2.0"
ignore = "0.4"
lazy_static = "1.4.0"
pest = "2.1.3"
pest_derive = "2.1.0"
regex = "1"
serde = {version = "1.0.127", features = ["derive"]}
serde_json = "1.0.66"
wasm-bindgen = {version = "0.2.75", features = ["serde-serialize"]}
wee_alloc = "0.4.5"

[dev-dependencies]
pretty_assertions = "1.0.0"

[profile.release]
# Tell `rustc` to optimize for small code size.
lto = true
opt-level = "s"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[features]
bench = []
