name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - "*"
    tags:
      - "*"
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    steps:
      - uses: actions/checkout@master
      - name: Install Rust
        run: rustup update stable && rustup default stable

      - name: Checkout
        uses: actions/checkout@v1

      - name: Test
        run: cargo test

  test_node:
    name: Test for Node.js
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"

      - name: Test Node.js
        run: |
          make test:node

  test_python:
    name: Test for Python
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install pytest
        run: python3 -m pip install pytest

      - name: Test Python
        run: make test:python

  test_ruby:
    name: Test for Ruby
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    steps:
      - uses: actions/checkout@v3

      - uses: oxidize-rb/actions/setup-ruby-and-rust@v1
        with:
          ruby-version: 3.1
          bundler-cache: true
          cargo-cache: true

      - name: Test Ruby
        run: make test:ruby

  test_java:
    strategy:
      fail-fast: true
      matrix:
        settings:
          - host: ubuntu-latest
          - host: macos-latest
    runs-on: ${{ matrix.settings.host }}
    name: Test for Java on ${{ matrix.settings.host }}
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    steps:
      - uses: actions/checkout@v3

      - name: Install JDK
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"

      - name: Test Java
        run: make test:java

  lint:
    name: Lint
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    steps:
      - uses: actions/checkout@master
      - name: Install Rust
        run: rustup update nightly && rustup default nightly

      - name: Checkout
        uses: actions/checkout@v1

      - name: Lint output
        run: make test:lint

      - name: Init test
        run: make test:init

      - name: Lint output JSON
        run: make test:lint-json
