name: CI
on:
  pull_request:
  push:
    branches:
      - "*"
      - "!build-test"
    tags:
      - "*"
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Rust
        run: rustup update stable && rustup default stable

      - name: Checkout
        uses: actions/checkout@v1

      - name: Test
        run: cargo test

  test_node:
    name: Test for Node.js
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"

      - name: Test Node.js
        run: |
          make test:node

  test_python:
    name: Test for Python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install pytest
        run: python3 -m pip install pytest

      - name: Test Python
        run: make test:python

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Rust
        run: rustup update nightly && rustup default nightly

      - name: Checkout
        uses: actions/checkout@v1

      - name: Lint output
        run: make test:lint

      - name: Init test
        run: make test:init

      - name: Lint output JSON
        run: make test:lint-json
