name: "Release RubyGem"
on:
  push:
    tags:
      - "v*"
    branches:
      - feat/ruby
jobs:
  build:
    name: Build compile gems
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-platform:
          - "arm64-darwin"
          - "x86_64-darwin"
          - "x86_64-linux"
    steps:
      - uses: actions/checkout@v3

      - uses: oxidize-rb/actions/setup-ruby-and-rust@main
        with:
          ruby-version: "3.1"
          bundler-cache: false
          cargo-cache: true
          cargo-vendor: true
          cache-version: v1

      - name: Touch Rakefile
        run: |
          touch Rakefile

      - uses: oxidize-rb/cross-gem-action@v6
        with:
          platform: ${{ matrix.ruby-platform }}
          directory: ./
          setup: cd autocorrect-rb/ && bundle install || gem install rb_sys

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: cross-gem
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "3.1"
      - name: Publish to RubyGems
        run: |
          gem push --key ${{ secrets.RUBYGEM_TOKEN }} autocorrect-rb/pkg/*.gem
