name: "Release RubyGem"
on:
  push:
    tags:
      - "v*"
    branches:
      - feat/ruby
jobs:
  build:
    name: Build compile gems
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-platform:
          - "arm64-darwin"
          - "x86_64-darwin"
          - "x86_64-linux"
    steps:
      - uses: actions/checkout@v3

      - uses: oxidize-rb/actions/setup-ruby-and-rust@main
        with:
          ruby-version: "3.1"
          bundler-cache: false
          cargo-cache: true
          cargo-vendor: true
          cache-version: v1

      - name: Touch Rakefile
        run: |
          touch Rakefile

      - uses: oxidize-rb/cross-gem-action@v6
        with:
          platform: ${{ matrix.ruby-platform }}
          directory: ./
          setup: cd autocorrect-rb/ && bundle install || gem install rb_sys
          env: |
            RUBY_CC_VERSION=3.1.0:3.0.0:2.7.0

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: cross-gem
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "3.1"
      - name: Publish to RubyGems
        env:
          RUBYGEM_TOKEN: "${{secrets.RUBYGEM_TOKEN}}"
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${RUBYGEM_TOKEN}\n" > $HOME/.gem/credentials
          for filename in autocorrect-rb/pkg/*.gem; do
            gem push $filename
          done
